server:
  port: 8989
  shutdown: graceful
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
            allowCredentials: false
      routes:
        - id: catalog-service
          uri: ${CATALOG_SERVICE_URL:http://localhost:18081}
          predicates:
            - Path=/catalog/**
          filters:
            - RewritePath=/catalog/(?<remaining>.*), /${remaining}

        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://localhost:18082}
          predicates:
            - Path=/orders/**
          filters:
            - RewritePath=/orders/(?<remaining>.*), /${remaining}

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator