server:
  port: 8989
  shutdown: graceful
spring:
  application:
    name: api-gateway

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator