# Exposes order-service inside the cluster as a ClusterIP service

apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082