include tools/make/docker.mk
include tools/make/help.mk
include tools/make/catalog-service.mk
include tools/make/ui.mk
include tools/make/app.mk
include tools/make/order-service.mk
include tools/make/api-gateway.mk
include tools/make/rabbitmq.mk
include tools/make/ingress.mk